# Generated by Django 5.2.5 on 2025-09-01 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controle", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                help_text="Usuário para acesso à área do cliente",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuário do Cliente",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="documento_final",
            field=models.FileField(
                blank=True,
                help_text="PDF/Laudo que será disponibilizado ao cliente após pagamento do 2º sinal",
                null=True,
                upload_to="documentos_finais/",
                verbose_name="Documento Final",
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="segundo_sinal_pago",
            field=models.BooleanField(
                default=False,
                help_text="Marcar como pago quando cliente efetuar o pagamento do segundo sinal",
                verbose_name="2º Sinal Pago",
            ),
        ),
    ]
