# Generated by Django 5.2.5 on 2025-09-04 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="Prisma Avaliações Imobiliárias",
                        max_length=100,
                        verbose_name="Nome do Site",
                    ),
                ),
                (
                    "site_domain",
                    models.CharField(
                        default="prismaavaliacoes.com.br",
                        help_text="Domínio sem http:// ou https://",
                        max_length=100,
                        verbose_name="Domínio do Site",
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        default="Avaliações imobiliárias profissionais e consultoria especializada",
                        help_text="Descrição padrão do site",
                        max_length=160,
                        verbose_name="Descrição do Site",
                    ),
                ),
                (
                    "default_keywords",
                    models.TextField(
                        default="avaliação imobiliária, laudo de avaliação, perícia imobiliária, consultoria imobiliária",
                        help_text="Palavras-chave padrão do site (separadas por vírgula)",
                        verbose_name="Palavras-chave Padrão",
                    ),
                ),
                (
                    "default_og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem padrão para compartilhamento (1200x630px)",
                        upload_to="seo/default/",
                        verbose_name="Imagem Padrão Open Graph",
                    ),
                ),
                (
                    "google_analytics_id",
                    models.CharField(
                        blank=True,
                        help_text="Ex: G-XXXXXXXXXX ou UA-XXXXXXXX-X",
                        max_length=20,
                        verbose_name="Google Analytics ID",
                    ),
                ),
                (
                    "google_tag_manager_id",
                    models.CharField(
                        blank=True,
                        help_text="Ex: GTM-XXXXXXX",
                        max_length=20,
                        verbose_name="Google Tag Manager ID",
                    ),
                ),
                (
                    "google_search_console_id",
                    models.CharField(
                        blank=True,
                        help_text="Código de verificação do Google Search Console",
                        max_length=100,
                        verbose_name="Google Search Console Verification",
                    ),
                ),
                (
                    "bing_webmaster_id",
                    models.CharField(
                        blank=True,
                        help_text="Código de verificação do Bing Webmaster",
                        max_length=100,
                        verbose_name="Bing Webmaster Verification",
                    ),
                ),
                (
                    "facebook_pixel_id",
                    models.CharField(
                        blank=True,
                        help_text="ID do Facebook Pixel",
                        max_length=20,
                        verbose_name="Facebook Pixel ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        default="Prisma Avaliações Imobiliárias",
                        max_length=100,
                        verbose_name="Nome da Organização",
                    ),
                ),
                (
                    "organization_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo para Schema.org Organization",
                        upload_to="seo/organization/",
                        verbose_name="Logo da Organização",
                    ),
                ),
                (
                    "organization_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Telefone da Organização",
                    ),
                ),
                (
                    "organization_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email da Organização"
                    ),
                ),
                (
                    "organization_address",
                    models.TextField(
                        blank=True, verbose_name="Endereço da Organização"
                    ),
                ),
                (
                    "sitemap_changefreq",
                    models.CharField(
                        choices=[
                            ("always", "Always"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("never", "Never"),
                        ],
                        default="weekly",
                        max_length=10,
                        verbose_name="Frequência de Mudança do Sitemap",
                    ),
                ),
                (
                    "sitemap_priority",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.8,
                        help_text="Prioridade padrão (0.0 a 1.0)",
                        max_digits=2,
                        verbose_name="Prioridade do Sitemap",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração SEO",
                "verbose_name_plural": "Configurações SEO",
            },
        ),
        migrations.CreateModel(
            name="SEOMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="ID do Objeto")),
                (
                    "title",
                    models.CharField(
                        help_text="Título otimizado para SEO (máximo 60 caracteres)",
                        max_length=60,
                        validators=[django.core.validators.MaxLengthValidator(60)],
                        verbose_name="Título SEO",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Descrição para mecanismos de busca (máximo 160 caracteres)",
                        max_length=160,
                        validators=[django.core.validators.MaxLengthValidator(160)],
                        verbose_name="Descrição SEO",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="Palavras-chave separadas por vírgula",
                        max_length=255,
                        verbose_name="Palavras-chave",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="URL canônica da página (deixe vazio para usar a URL atual)",
                        verbose_name="URL Canônica",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Impedir indexação nos mecanismos de busca",
                        verbose_name="No Index",
                    ),
                ),
                (
                    "nofollow",
                    models.BooleanField(
                        default=False,
                        help_text="Impedir que robôs sigam os links desta página",
                        verbose_name="No Follow",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True,
                        help_text="Título para redes sociais (Facebook, LinkedIn)",
                        max_length=60,
                        verbose_name="Título Open Graph",
                    ),
                ),
                (
                    "og_description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição para redes sociais",
                        max_length=160,
                        verbose_name="Descrição Open Graph",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem para compartilhamento (recomendado: 1200x630px)",
                        upload_to="seo/og_images/",
                        verbose_name="Imagem Open Graph",
                    ),
                ),
                (
                    "og_type",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("article", "Artigo"),
                            ("blog", "Blog"),
                            ("product", "Produto"),
                            ("business", "Negócio"),
                        ],
                        default="website",
                        help_text="Tipo de conteúdo para Open Graph",
                        max_length=20,
                        verbose_name="Tipo Open Graph",
                    ),
                ),
                (
                    "twitter_card",
                    models.CharField(
                        choices=[
                            ("summary", "Summary"),
                            ("summary_large_image", "Summary Large Image"),
                            ("app", "App"),
                            ("player", "Player"),
                        ],
                        default="summary_large_image",
                        help_text="Tipo de Twitter Card",
                        max_length=20,
                        verbose_name="Twitter Card",
                    ),
                ),
                (
                    "twitter_title",
                    models.CharField(
                        blank=True,
                        help_text="Título para Twitter",
                        max_length=60,
                        verbose_name="Título Twitter",
                    ),
                ),
                (
                    "twitter_description",
                    models.TextField(
                        blank=True,
                        help_text="Descrição para Twitter",
                        max_length=160,
                        verbose_name="Descrição Twitter",
                    ),
                ),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem para Twitter Cards",
                        upload_to="seo/twitter_images/",
                        verbose_name="Imagem Twitter",
                    ),
                ),
                (
                    "schema_markup",
                    models.TextField(
                        blank=True,
                        help_text="Código JSON-LD para dados estruturados Schema.org",
                        verbose_name="Schema Markup (JSON-LD)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Tipo de Conteúdo",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Meta",
                "verbose_name_plural": "SEO Metas",
                "ordering": ["-updated_at"],
                "unique_together": {("content_type", "object_id")},
            },
        ),
    ]
