# Generated by Django 5.2.5 on 2025-08-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(
                        help_text="Título do artigo (máximo 200 caracteres)",
                        max_length=200,
                        verbose_name="Título",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL do artigo (gerada automaticamente a partir do título)",
                        max_length=200,
                        unique=True,
                        verbose_name="URL amigável",
                    ),
                ),
                (
                    "autor",
                    models.CharField(
                        help_text="Nome do autor do artigo",
                        max_length=100,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "resumo",
                    models.TextField(
                        help_text="Resumo do artigo para exibição na listagem (máximo 300 caracteres)",
                        max_length=300,
                        verbose_name="Resumo",
                    ),
                ),
                (
                    "conteudo",
                    models.TextField(
                        help_text="Conteúdo completo do artigo", verbose_name="Conteúdo"
                    ),
                ),
                (
                    "imagem_destacada",
                    models.ImageField(
                        blank=True,
                        help_text="Imagem principal do artigo (opcional)",
                        null=True,
                        upload_to="artigos/imagens/",
                        verbose_name="Imagem destacada",
                    ),
                ),
                (
                    "publicado",
                    models.BooleanField(
                        default=False,
                        help_text="Marque para publicar o artigo",
                        verbose_name="Publicado",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de criação"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        blank=True,
                        help_text="Data em que o artigo foi publicado",
                        null=True,
                        verbose_name="Data de publicação",
                    ),
                ),
                (
                    "data_atualizacao",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última atualização"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Descrição para SEO (máximo 160 caracteres)",
                        max_length=160,
                        verbose_name="Meta descrição",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Tags separadas por vírgula (ex: avaliação, imóveis, mercado)",
                        max_length=200,
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artigo",
                "verbose_name_plural": "Artigos",
                "ordering": ["-data_publicacao", "-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, unique=True, verbose_name="Nome"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=100,
                        unique=True,
                        verbose_name="URL amigável",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
                "ordering": ["nome"],
            },
        ),
    ]
