# Generated by Django 5.2.5 on 2025-09-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0002_change_autor_to_charfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="artigo",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="URL canônica se diferente da padrão (opcional)",
                verbose_name="URL canônica",
            ),
        ),
        migrations.AddField(
            model_name="artigo",
            name="meta_keywords",
            field=models.CharField(
                blank=True,
                help_text="Palavras-chave separadas por vírgula para SEO",
                max_length=255,
                verbose_name="Palavras-chave",
            ),
        ),
    ]
