# Generated by Django 5.2.5 on 2025-09-01 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0003_artigo_canonical_url_artigo_meta_keywords"),
    ]

    operations = []
